import PDFDocument from "pdfkit";
import { requireUserForApi } from "@/lib/auth/api";
import { getPlanDetail } from "@/lib/plan/queries";
import { goalPaceSecPerKm } from "@/lib/plan/goal";
import { paceZones } from "@/lib/plan/vdot";
import { isoDayOfWeek } from "@/lib/plan/dates";
import { PHASE_META, raceLabel, WORKOUT_META } from "@/lib/planMeta";
import type { WorkoutSegment } from "@/lib/plan/types";
import {
  distanceIn,
  formatDistance,
  formatDuration,
  formatPace,
  formatPaceRange,
  type Unit,
} from "@/lib/units";

export const dynamic = "force-dynamic";

const DAYNAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function fmtDate(iso: string): string {
  const [, m, d] = iso.split("-").map(Number);
  return `${DAYNAMES[isoDayOfWeek(iso) - 1]} ${d} ${MONTHS[m - 1]}`;
}

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireUserForApi();
  if (!auth.ok) return auth.response;
  const { id } = await params;
  const plan = await getPlanDetail(auth.user.id, id);
  if (!plan) return new Response("Not found", { status: 404 });

  const unit: Unit = auth.user.unitPref;
  const goalPace = goalPaceSecPerKm(plan.raceType, plan.goalTimeS, plan.customDistanceKm);
  const easyZ = paceZones(plan.currentVdot);
  const goalZ = paceZones(plan.goalVdot);

  const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const contentW = right - left;
  const bottom = doc.page.height - doc.page.margins.bottom;

  // ---- Header ------------------------------------------------------------
  doc.rect(0, 0, doc.page.width, 96).fill("#4f46e5");
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(20).text(plan.name, left, 26);
  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#e0e7ff")
    .text(
      `${raceLabel(plan.raceType, plan.customDistanceKm, unit)}  ·  Goal ${formatDuration(plan.goalTimeS)}  ·  ${formatPace(goalPace, unit)}  ·  Race ${fmtDate(plan.raceDate)}`,
      left,
      54,
    );
  doc.fontSize(9).fillColor("#c7d2fe").text("Generated by RunPlan · Pfitzinger volume · Daniels VDOT pacing", left, 72);

  let y = 116;

  // ---- Pace guide --------------------------------------------------------
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f1729").text("Training paces", left, y);
  y += 18;
  const paces: [string, string][] = [
    ["Easy", formatPaceRange(easyZ.easyFast, easyZ.easySlow, unit)],
    ["Race pace", formatPace(goalPace, unit)],
    ["Threshold", formatPace(goalZ.threshold, unit)],
    ["Interval", formatPace(goalZ.interval, unit)],
    ["Recovery", formatPace(easyZ.recovery, unit)],
  ];
  const pw = contentW / paces.length;
  paces.forEach(([label, val], i) => {
    const x = left + i * pw;
    doc.roundedRect(x, y, pw - 8, 40, 6).fill("#f1f3f6");
    doc.fillColor("#5b6472").font("Helvetica").fontSize(8).text(label.toUpperCase(), x + 8, y + 8, { width: pw - 20 });
    doc.fillColor("#0f1729").font("Helvetica-Bold").fontSize(12).text(val, x + 8, y + 20, { width: pw - 20 });
  });
  y += 58;

  // ---- Weeks -------------------------------------------------------------
  const ROW_H = 15;
  const cols = { day: left + 6, type: left + 78, dist: left + 132, pace: left + 192, desc: left + 268 };
  const descW = right - cols.desc - 6;

  for (const week of plan.weeks) {
    const needed = 22 + week.workouts.length * ROW_H + 10;
    if (y + needed > bottom) {
      doc.addPage();
      y = doc.page.margins.top;
    }

    const meta = PHASE_META[week.phase];
    doc.roundedRect(left, y, contentW, 20, 4).fill(meta.color);
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(10).text(
      `WEEK ${week.weekIndex + 1}  ·  ${meta.label}${week.isCutback ? "  ·  cutback" : ""}`,
      left + 8,
      y + 6,
    );
    doc.font("Helvetica").fontSize(10).text(
      `${formatDistance(week.plannedVolumeKm, unit, 0)} planned`,
      left,
      y + 6,
      { width: contentW - 10, align: "right" },
    );
    y += 26;

    for (const d of week.workouts) {
      const wm = WORKOUT_META[d.type];
      const isRest = d.type === "rest";
      doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#0f1729").text(fmtDate(d.date), cols.day, y + 3, { width: 66, lineBreak: false });
      doc.fillColor(wm.color).font("Helvetica-Bold").fontSize(8.5).text(wm.short, cols.type, y + 3, { width: 52, lineBreak: false });
      if (!isRest) {
        doc.fillColor("#0f1729").font("Helvetica").fontSize(8.5).text(
          formatDistance(d.distanceKm, unit, d.distanceKm % 1 === 0 ? 0 : 1),
          cols.dist,
          y + 3,
          { width: 56, lineBreak: false },
        );
        const pace =
          d.paceLowSPerKm != null
            ? d.paceHighSPerKm != null && d.paceHighSPerKm !== d.paceLowSPerKm
              ? formatPaceRange(d.paceLowSPerKm, d.paceHighSPerKm, unit)
              : formatPace(d.paceLowSPerKm, unit)
            : "";
        doc.fillColor("#5b6472").text(pace, cols.pace, y + 3, { width: 74, lineBreak: false });
      }
      const segs = (d.segments as WorkoutSegment[] | null) ?? null;
      const descFull = segs && segs.length ? `${d.description} — ${segs.map((s) => s.label).join("; ")}` : d.description;
      // Measure and truncate to fit one line, then draw without a width so pdfkit
      // cannot wrap (its lineBreak:false is unreliable when a width is set).
      doc.font("Helvetica").fontSize(8.5);
      let desc = descFull;
      if (doc.widthOfString(desc) > descW) {
        while (desc.length > 1 && doc.widthOfString(`${desc}…`) > descW) desc = desc.slice(0, -1);
        desc = `${desc.trimEnd()}…`;
      }
      doc.fillColor(isRest ? "#97a0ae" : "#5b6472").text(desc, cols.desc, y + 3, { lineBreak: false });
      if (d.completed) {
        // Standard PDF fonts lack a tick glyph — draw a small "done" dot instead.
        doc.circle(left - 2, y + 7, 2.4).fill("#10b981");
      }
      y += ROW_H;
    }
    y += 8;
  }

  // ---- Footer page numbers ----------------------------------------------
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.font("Helvetica").fontSize(8).fillColor("#97a0ae").text(
      `Page ${i + 1} of ${range.count}`,
      left,
      doc.page.height - 28,
      { width: contentW, align: "center" },
    );
  }

  doc.end();
  const buf = await done;

  const filename = `${plan.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`;
  return new Response(new Uint8Array(buf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
